repos:
  - repo: local
    hooks:
      - id: generate-stubs
        name: Generate FluentPipe protocol stubs
        entry: ./scripts/run-hook.sh uv run scripts/gen_stubs.py  --source src/samples/fluent_pipeline.py --output src/samples/protocol_stubs.py
        language: system
        files: ^src/samples/fluent_pipeline\.py$
        pass_filenames: false

  - repo: local
    hooks:
      - id: ty-check
        name: ⚡ ty check (instant typing)
        entry: ./scripts/run-hook.sh uv run ty check
        language: system
        pass_filenames: false # Always run on the whole project for safety
        always_run: true

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.1
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 4.2.2
    hooks:
      - id: sqlfluff-lint
        args: [--config, ./pyproject.toml]
      - id: sqlfluff-fix
        args: [--config, ./pyproject.toml]