# ==============================================================================
# THIS FILE IS AUTOGENERATED - DO NOT EDIT MANUALLY
# Use scripts/gen_stubs.py to regenerate this file.
# ==============================================================================

from typing import Any, Protocol


# noinspection PyUnresolvedReferences
class FluentPipeProtocol(Protocol):
    """Auto-generated Protocol for IDE support of FluentPipe steps."""

    def sample_filter1(self, mul: int) -> "FluentPipeProtocol":
        """Sample filter function that multiplies list elements.

        This is a demonstration function for the fluent pipeline.
        It creates a new list by repeating the original list 'mul' times.
        `data` value is implicit in pipeline call
        :param mul: The multiplier for list repetition.

        :return: The multiplied list.

        Example:
            >>> sample_filter1([1, 2], mul=3)
            [1, 2, 1, 2, 1, 2]"""
        ...

    def sample_filter2(self) -> "FluentPipeProtocol":
        """Sample identity function for testing pipelines.

        This function simply returns the input data unchanged.
        It's useful for testing pipeline structure and flow.
        `data` value is implicit in pipeline call

        :return: The same data that was passed in.

        Example:
            >>> sample_filter2([1, 2, 3])
            [1, 2, 3]"""
        ...

    def sample_add_to_values(self, value: str) -> "FluentPipeProtocol":
        """Sample function that adds a suffix to all string values in dictionaries.

        This function iterates through a list of dictionaries and adds the
        provided value to all string values in each dictionary using toolz.valmap.
        `data` value is implicit in pipeline call
        :param value: The string value to append to all string values.

        :return: A new list of dictionaries with modified string values.

        Example:
            >>> sample_add_to_values([{'a': '1', 'b': '2'}], value='_test')
            [{'a': '1_test', 'b': '2_test'}]"""
        ...

    def execute(self) -> Any: ...
