import ast
import os

from icecream import ic


def generate_stubs(source_file: str, output_file: str) -> None:
    """Parses a Python file, finds @pipeable functions, and generates a Protocol stub."""

    with open(source_file) as f:
        tree = ast.parse(f.read())

    pipeable_funcs = []

    for node in tree.body:
        if isinstance(node, ast.FunctionDef):
            is_pipeable = any(
                (isinstance(decorator, ast.Name) and decorator.id == "pipeable")
                or (
                    isinstance(decorator, ast.Call)
                    and isinstance(decorator.func, ast.Name)
                    and decorator.func.id == "pipeable"
                )
                for decorator in node.decorator_list
            )

            if is_pipeable:
                # Extract arguments skipping the first one (usually 'data')
                args = node.args
                # We want to skip the first positional argument
                other_args = []

                # Handle positional args
                for i, arg in enumerate(args.args):
                    if i == 0:
                        continue  # Skip 'data'
                    arg_str = arg.arg
                    if arg.annotation:
                        arg_str += f": {ast.unparse(arg.annotation)}"
                    other_args.append(arg_str)

                # Handle keyword-only args
                for kwarg in args.kwonlyargs:
                    arg_str = kwarg.arg
                    if kwarg.annotation:
                        arg_str += f": {ast.unparse(kwarg.annotation)}"
                    # In protocols, we often want to reflect if it has a default
                    # but for simplicity we'll just list them.
                    other_args.append(arg_str)

                docstring = ast.get_docstring(node)
                pipeable_funcs.append({"name": node.name, "args": other_args, "doc": docstring})

    # Build the stub file content
    lines = [
        "# " + "=" * 78,
        "# THIS FILE IS AUTOGENERATED - DO NOT EDIT MANUALLY",
        "# Use scripts/gen_stubs.py to regenerate this file.",
        "# " + "=" * 78,
        "",
        "from typing import Any, Protocol",
        "",
        "class FluentPipeProtocol(Protocol):",
        '    """Auto-generated Protocol for IDE support of FluentPipe steps."""',
        "",
    ]

    for func in pipeable_funcs:
        arg_list = ", ".join(["self"] + func["args"])
        lines.append(f'    def {func["name"]}({arg_list}) -> "FluentPipeProtocol":')
        if func["doc"]:
            lines.append(f'        """{func["doc"]}"""')
        lines.append("        ...")
        lines.append("")

    lines.append("    def execute(self) -> Any:")
    lines.append("        ...")

    with open(output_file, "w") as f:
        f.write("\n".join(lines))

    ic(f"Successfully generated stubs in {output_file}")


if __name__ == "__main__":
    src = "src/samples/fluent_pipeline.py"
    out = "src/samples/protocol_stubs.py"

    # Ensure directories exist
    os.makedirs(os.path.dirname(out), exist_ok=True)

    generate_stubs(src, out)
