import ast
import os
import subprocess
from typing import Any

from icecream import ic


def _is_pipeable(node: ast.FunctionDef) -> bool:
    """Check if a function definition is decorated with @pipeable."""
    return any(
        (isinstance(decorator, ast.Name) and decorator.id == "pipeable")
        or (
            isinstance(decorator, ast.Call)
            and isinstance(decorator.func, ast.Name)
            and decorator.func.id == "pipeable"
        )
        for decorator in node.decorator_list
    )


def _extract_arguments(args: ast.arguments) -> list[str]:
    """Extract arguments from a function, skipping the first one (usually 'data')."""
    other_args = []

    # Handle positional args
    for i, arg in enumerate(args.args):
        if i == 0:
            continue  # Skip 'data'
        arg_str = arg.arg
        if arg.annotation:
            arg_str += f": {ast.unparse(arg.annotation)}"
        other_args.append(arg_str)

    # Handle keyword-only args
    for kwarg in args.kwonlyargs:
        arg_str = kwarg.arg
        if kwarg.annotation:
            arg_str += f": {ast.unparse(kwarg.annotation)}"
        other_args.append(arg_str)

    return other_args


def _get_pipeable_functions(tree: ast.Module) -> list[dict[str, Any]]:
    """Traverse the AST to find all @pipeable functions and extract metadata."""
    return [
        {
            "name": node.name,
            "args": _extract_arguments(node.args),
            "doc": ast.get_docstring(node),
        }
        for node in tree.body
        if isinstance(node, ast.FunctionDef) and _is_pipeable(node)
    ]


def _generate_stub_lines(pipeable_funcs: list[dict[str, Any]]) -> list[str]:
    """Generate the lines for the protocol stub file."""
    lines = [
        "# " + "=" * 78,
        "# THIS FILE IS AUTOGENERATED - DO NOT EDIT MANUALLY",
        "# Use scripts/gen_stubs.py to regenerate this file.",
        "# " + "=" * 78,
        "",
        "from typing import Any, Protocol",
        "",
        "class FluentPipeProtocol(Protocol):",
        '    """Auto-generated Protocol for IDE support of FluentPipe steps."""',
        "",
    ]

    for func in pipeable_funcs:
        arg_list = ", ".join(["self"] + func["args"])
        lines.append(f'    def {func["name"]}({arg_list}) -> "FluentPipeProtocol":')
        if func["doc"]:
            lines.append(f'        """{func["doc"]}"""')
        lines.append("        ...")
        lines.append("")

    lines.append("    def execute(self) -> Any:")
    lines.append("        ...")
    return lines


def generate_stubs(source_file: str, output_file: str) -> None:
    """Parses a Python file, finds @pipeable functions, and generates a Protocol stub."""
    with open(source_file) as f:
        tree = ast.parse(f.read())

    pipeable_funcs = _get_pipeable_functions(tree)
    lines = _generate_stub_lines(pipeable_funcs)

    with open(output_file, "w") as f:
        f.write("\n".join(lines))

    ic(f"Successfully generated stubs in {output_file}")


if __name__ == "__main__":
    src = "src/samples/fluent_pipeline.py"
    out = "src/samples/protocol_stubs.py"

    # Ensure directories exist
    os.makedirs(os.path.dirname(out), exist_ok=True)

    generate_stubs(src, out)
    # Immediately format the file so pre-commit is happy
    subprocess.run(["uv", "run", "ruff", "format", out])
    exit(0)
