import ast
import os
import re
from typing import Any

import loguru
from jinja2 import Template

logger = loguru.logger

fluent_pipe_protocol_tpl = '''# {{ "=" * 78 }}
# THIS FILE IS AUTOGENERATED - DO NOT EDIT MANUALLY
# Use scripts/gen_stubs.py to regenerate this file.
# {{ "=" * 78 }}

from typing import Any, Protocol


# noinspection PyUnresolvedReferences
class FluentPipeProtocol(Protocol):
    """Auto-generated Protocol for IDE support of FluentPipe steps."""
{% for func in pipeable_funcs %}
    def {{ func.name }}(self
    {%- if func.args -%}
        , {{ func.args | join(", ") }}
    {%- endif -%}) -> "FluentPipeProtocol":
{%- if func.doc %}
        """{{ func.doc | indent(8, False) }}"""
{% endif %}        ...
{% endfor %}
    def execute(self) -> Any: ...

'''


def _is_pipeable(node: ast.FunctionDef) -> bool:
    """Check if a function definition is decorated with @pipeable."""
    return any(
        (isinstance(decorator, ast.Name) and decorator.id == "pipeable")
        or (
            isinstance(decorator, ast.Call)
            and isinstance(decorator.func, ast.Name)
            and decorator.func.id == "pipeable"
        )
        for decorator in node.decorator_list
    )


def _extract_arguments(args: ast.arguments) -> list[str]:
    """Extract arguments from a function, skipping the first one (usually 'data')."""
    other_args = []

    # Handle positional args
    for i, arg in enumerate(args.args):
        if i == 0:
            continue  # Skip 'data'
        arg_str = arg.arg
        if arg.annotation:
            arg_str += f": {ast.unparse(arg.annotation)}"
        other_args.append(arg_str)

    # Handle keyword-only args
    for kwarg in args.kwonlyargs:
        arg_str = kwarg.arg
        if kwarg.annotation:
            arg_str += f": {ast.unparse(kwarg.annotation)}"
        other_args.append(arg_str)

    return other_args


def _explain_data_var(docstring: str) -> str:
    return re.sub(r"\n:param data:.*\n", "`data` value is implicit in pipeline call\n", docstring)


def _get_pipeable_functions(tree: ast.Module) -> list[dict[str, Any]]:
    """Traverse the AST to find all @pipeable functions and extract metadata."""
    return [
        {
            "name": node.name,
            "args": _extract_arguments(node.args),
            "doc": _explain_data_var(ast.get_docstring(node)),
        }
        for node in tree.body
        if isinstance(node, ast.FunctionDef) and _is_pipeable(node)
    ]


def _generate_stub_lines(pipeable_funcs: list[dict[str, Any]]) -> str:
    """Generate the content for the protocol stub file using Jinja2 template."""
    global fluent_pipe_protocol_tpl

    template = Template(fluent_pipe_protocol_tpl)
    return template.render(pipeable_funcs=pipeable_funcs)


def generate_stubs(source_file: str, output_file: str) -> None:
    """Parses a Python file, finds @pipeable functions, and generates a Protocol stub."""
    with open(source_file) as f:
        tree = ast.parse(f.read())

    pipeable_funcs = _get_pipeable_functions(tree)
    content = _generate_stub_lines(pipeable_funcs)

    with open(output_file, "w") as f:
        f.write(content)

    logger.info(f"Successfully generated stubs in {output_file}")


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="Generate stubs from pipeable functions.")
    parser.add_argument(
        "--source", "-s", default="src/samples/fluent_pipeline.py", help="Path to the source file"
    )
    parser.add_argument(
        "--output",
        "-o",
        default="src/samples/protocol_stubs.py",
        help="Path to the output stub file",
    )

    args = parser.parse_args()

    src = args.source
    out = args.output

    # Ensure directories exist
    os.makedirs(os.path.dirname(out), exist_ok=True)

    generate_stubs(src, out)
    # Immediately format the file so pre-commit is happy
    # subprocess.run(["uv", "run", "ruff", "format", out])
    exit(0)
